In [1]:
import tensorflow as tf

# ones
x = tf.ones(shape=(2,1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [3]:
# zeros
x = tf.zeros(shape=(2,1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

In [4]:
# random values from nomral distribution
x = tf.random.normal(shape=(2,1), mean=0, stddev=1)
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.15351917],
       [ 0.35991177]], dtype=float32)>

In [5]:
# radom values from uniform distribution
x = tf.random.uniform(shape=(2,1), minval=-1, maxval=1)
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.20237708],
       [ 0.29852366]], dtype=float32)>

In [6]:
# difference to numpy tensors, tf-tensors are constant
# for exampe:

import numpy as np
a = np.ones(shape=(2,2))
b = tf.ones(shape=(2,2))

a[0][0] = 5

try:
    b[0][0] = 5
except:
    print("not possible")

print(f"numpy: {a}\ntensorflow: {b}")

not possible
numpy: [[5. 1.]
 [1. 1.]]
tensorflow: [[1. 1.]
 [1. 1.]]
