# Tensors

In [1]:
import tensorflow as tf

# ones
x = tf.ones(shape=(2,1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [3]:
# zeros
x = tf.zeros(shape=(2,1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

In [4]:
# random values from nomral distribution
x = tf.random.normal(shape=(2,1), mean=0, stddev=1)
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.15351917],
       [ 0.35991177]], dtype=float32)>

In [5]:
# radom values from uniform distribution
x = tf.random.uniform(shape=(2,1), minval=-1, maxval=1)
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.20237708],
       [ 0.29852366]], dtype=float32)>

In [6]:
# difference to numpy tensors, tf-tensors are constant
# for exampe:

import numpy as np
a = np.ones(shape=(2,2))
b = tf.ones(shape=(2,2))

a[0][0] = 5

try:
    b[0][0] = 5
except:
    print("not possible")

print(f"numpy: {a}\ntensorflow: {b}")

not possible
numpy: [[5. 1.]
 [1. 1.]]
tensorflow: [[1. 1.]
 [1. 1.]]


# Variables

In [8]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3,1), mean=5, stddev=1))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[5.923983 ],
       [5.1465592],
       [4.4586024]], dtype=float32)>

In [9]:
# variables are reassignable
v = v.assign(tf.ones(shape=(3,1)))
v

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [12]:
v[0, 0].assign(3)
v

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

In [13]:
# add
v.assign_add(tf.ones(shape=(3,1)))
v

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

# Mathmatical operations

In [58]:
a = tf.Variable(initial_value=tf.ones((2, 2)))
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [59]:
a.assign_add(tf.ones((2,2)))
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [60]:
a = tf.square(a)
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [61]:
a = tf.sqrt(a)
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [62]:
a = tf.matmul(a, tf.constant([[1, 1,1 ], [1, 1, 1],], dtype="float32"))
a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4., 4., 4.],
       [4., 4., 4.]], dtype=float32)>

# Calculate gradient of diff. expression

In [71]:
input_var = tf.Variable(initial_value=3.)

with tf.GradientTape() as tape:
    tape.watch(input_var)
    result = tf.square(input_var) # x*x
dy_dx = tape.gradient(result, input_var) # 2*x

print(dy_dx)

tf.Tensor(6.0, shape=(), dtype=float32)


In [70]:
with tf.GradientTape() as tape_1:
    tape_1.watch(input_var)
    
    with tf.GradientTape() as tape_2:
        tape_2.watch(input_var)
        y = tf.square(input_var) # x*x
    dy_dx = tape_2.gradient(y, input_var) # 2*x
    print(f"dy_dx: {dy_dx}")

d2y_d2x = tape_1.gradient(dy_dx, input_var) # 2
print(f"d2y_dx2: {d2y_d2x}")

dy_dx: 6.0
d2y_dx2: 2.0
